#!/bin/bash

git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/ApplicationInsightsLand.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/AzureBoardsLand.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/AzureDatalakeToolsForLand.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/AzureIOTDeveloperKit.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/AzurePipelinesLand.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/AzureReposLand.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/AzureStreamAnalyticsInLand.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/Codetour.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/ComposeLanguageService.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/DeoptexplorerLand.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/DevSkim.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/DevSkimLandPlugin.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/DSToolkitDevContainers.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/Editor.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/Gnls.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandAnacondaExtensionPack.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandAnycode.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandApimanagement.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandAppcenter.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandArduino.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandAsa.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandAtomKeybindings.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandAutopep8.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandAzureAccount.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandAzureAppService.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandAzureArmTools.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandAzureAutomation.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandAzureBlockchainEthereum.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandAzureCache.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandAzureCli.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandAzureCognitiveSearch.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandAzureContainerapps.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandAzureEventGrid.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandAzureFunctions.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandAzureFunctionsRemoteWebExtension.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandAzureHealthcareAPIsTools.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandAzureIOTEdge.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandAzureIOTToolkit.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandAzureIOTTools.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandAzureLogicapps.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandAzurePack.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandAzureResourceGroups.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandAzureServerlessPack.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandAzureSpringCloud.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandAzureStaticwebapps.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandAzureStorage.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandAzureTools.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandAzureVirtualMachines.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandBackSpace.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandBisect.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandBlackFormatter.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandBracketsKeybindings.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandBracketsPack.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandCdp.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandCdpProxy.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandChromeDebug.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandChromeDebugCore.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandCmakeTools.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandCmakeToolsApi.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandCodicons.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandComment.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandCopilotRelease.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandCordova.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandCosmosDB.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandCosmosDBGraph.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandCourseSample.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandCPPTools.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandCPPToolsApi.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandCSS.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandCSSLanguageService.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandCustomData.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandDAPR.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandDataWrangler.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandDebugAdapterNode.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandDeployAzure.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandDevChromeLauncher.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandDevContainers.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandDiagnosticTools.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandDiscussions.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandDocker.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandDockerExtensibility.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandDocs.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandDocsArchive.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandDocsAuthoring.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandDotNETTools.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandDtdl.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandDts.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandDwarfDebugging.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandDwarfDebuggingExt.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandEdgeDebug.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandEdgeDebug2.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandEdgeDevTools.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandEdgeDevToolsNetwork.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandEditorConfig.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandEmbeddedTools.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandEmmetHelper.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandEmmetLegacy.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandESLint.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandExplorerCommand.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandExtensionLand.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandExtensionRecommender.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandExtensionSamples.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandExtensionTelemetry.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandExtensionTestRunner.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandFigmaIcons.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandFigmaToolkit.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandFileDownloader.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandFileDownloaderApi.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandFilewatcherWindows.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandFlake8.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandGather.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandGeneratorCode.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandGeneratorCodeJavascript.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandGitHubIssueNotebooks.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandGitHubIssuesPrs.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandGitHubTriageActions.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandGitHubTriageExtension.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandGo.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandGradle.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandGrammarUpdater.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandGulpElectron.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandHexEditor.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandHTMLHint.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandHTMLLanguageService.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandHTMLTagWrap.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandHydrate.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandIcons.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandIconvLiteUMD.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandIosWebDebug.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandIOTWorkbench.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandIsort.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandJavaDebug.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandJavaDependency.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandJavaInstaller.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandJavaPack.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandJavaTest.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandJSAtomGrammar.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandJSCS.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandJSDebug.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandJSDebugBrowsers.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandJSDebugCompanion.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandJSHint.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandJSON.tmLanguage.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandJSonLanguageService.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandJSProfileVisualizer.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandJupyter.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandJupyterCellTags.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandJupyterHub.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandJupyterIpywidgets.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandJupyterKeymap.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandJupyterLSPMiddleware.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandJupyterPowertoys.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandJupyterSlideshow.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandJvmTools.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandL10n.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandLanguageDetection.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandLanguageServerNode.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandLanguageServerProtocolFoldingprovider.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandLaTeX.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandLinuxBuildAgent.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandLivePreview.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandLoader.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandLoc.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandLocDeprecated.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandLombok.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandLsifExtension.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandMakecode.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandMakefileTools.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandMarkdownItKatex.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandMarkdownLanguageService.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandMarkdownNotebook.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandMarkdownTmGrammar.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandMaven.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandMDTools.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandMezzurite.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandMinimist.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandMockDebug.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandMongoDB.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandMonoDebug.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandMssql.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandMypy.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandNls.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandNlsDev.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandNodeAzurePack.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandNodebook.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandNodeDebug.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandNodeDebug2.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandNodeSQLite3.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandNotebookErrorOverlay.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandNotebookRenderers.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandNotebookRendererStarter.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandNotebookTestData.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandNotepadPlusPlusKeybindings.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandNPMScripts.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandOcticonsFont.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandOnedriveBrowser.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandOniguruma.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandOpenSSLPrebuilt.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandPerf.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandPerfBot.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandPlatformSpecificSample.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandPolicyWatcher.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandPostgresql.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandPowerquery.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandPowerquerySdk.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandProxyAgent.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandPullRequestGitHub.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandPwaAnalyzer.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandPylint.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandPython.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandPythonDebugger.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandPythonDeviceSimulator.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandPythonDsExtensionPack.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandPythonInstaller.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandPythonToolsExtensionTemplate.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandPythonWebWASM.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandReactNative.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandReactSample.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandRecipes.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandReferencesView.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandRemoteRelease.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandRemoteRepositoriesGitHub.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandRemoteTryCPP.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandRemoteTryDotNET.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandRemoteTryGo.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandRemoteTryJava.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandRemoteTryNode.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandRemoteTryPhp.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandRemoteTryPython.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandRemoteTryRust.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandRemoteTrySQLserver.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandRemoteWSLRecommender.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandResharperKeybindings.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandRipGREP.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandRussh.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandSamples.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandSCMBuilders.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandSecretServiceRs.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandSelfhostTestProvider.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandSerialMonitor.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandServiceFabricReliableServices.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandServiceStatus.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandSimpleJupyterNotebook.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandSmokeTestCheck.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandSmokeTestExpress.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandspacesQuickstart.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandSpellCheck.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandSpringBootDashboard.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandSpringInitializr.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandStac.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandSublimeKeybindings.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandTasAngular.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandTasExpress.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandTasVue.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandTeam.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandTelemetryExtractor.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandTensorboard.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandTest.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandTestAdapterConverter.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandTestCli.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandTestCover.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandTestWeb.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandTextBuffer.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandTextMate.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandThemeColorConsumer.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandThemes.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandThemeTester.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandTipsAndTricks.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandTMDL.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandToolsForAI.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandTSLint.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandTSPackageManager.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandTSTSLint.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandTye.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandTypeScriptNext.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandTypeScriptTSLintPlugin.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandURI.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandV8HeapTools.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandVSCE.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandVSKeybindings.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandWASM.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandWebPlayground.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandWebViewUIToolkit.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandWebViewUIToolkitSamples.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandWiki.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandWin32AppContainerTokens.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandWindowsCaCerts.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandWindowsProcessTree.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandWindowsRegistry.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandWinsta11er.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandWordCount.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LandZeroMQ.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LinkCheckerMD.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/MonacoEditor.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/NodeRequestLight.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/PlaywrightLand.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/PowerPlatformLand.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/PowerPlatformLandLab.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/PSDocsLand.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/PSRuleLand.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/PVSCBot.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/PythonSampleLandDjangoTutorial.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/PythonSampleLandFastapiTutorial.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/PythonSampleLandFlaskTutorial.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/Quantum.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/SarifLandExtension.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/ScopeStudioLand.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/SynapseLand.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/ThemeConverterForVS.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TypeScriptLandExtensions.git
