#!/bin/bash

git submodule add ssh://git@github.com/CodeEditorLand/ApplicationinsightsLand.git ApplicationinsightsLand
git submodule add ssh://git@github.com/CodeEditorLand/AzureBoardsLand.git AzureBoardsLand
git submodule add ssh://git@github.com/CodeEditorLand/AzureDatalakeToolsForLand.git AzureDatalakeToolsForLand
git submodule add ssh://git@github.com/CodeEditorLand/AzureIotDeveloperKit.git AzureIotDeveloperKit
git submodule add ssh://git@github.com/CodeEditorLand/AzurePipelinesLand.git AzurePipelinesLand
git submodule add ssh://git@github.com/CodeEditorLand/AzureReposLand.git AzureReposLand
git submodule add ssh://git@github.com/CodeEditorLand/AzureStreamAnalyticsInLand.git AzureStreamAnalyticsInLand
git submodule add ssh://git@github.com/CodeEditorLand/Codetour.git Codetour
git submodule add ssh://git@github.com/CodeEditorLand/ComposeLanguageService.git ComposeLanguageService
git submodule add ssh://git@github.com/CodeEditorLand/DeoptexplorerLand.git DeoptexplorerLand
git submodule add ssh://git@github.com/CodeEditorLand/DevSkim.git DevSkim
git submodule add ssh://git@github.com/CodeEditorLand/DevSkimLandPlugin.git DevSkimLandPlugin
git submodule add ssh://git@github.com/CodeEditorLand/DstoolkitDevcontainers.git DstoolkitDevcontainers
git submodule add ssh://git@github.com/CodeEditorLand/Gnls.git Gnls
git submodule add ssh://git@github.com/CodeEditorLand/Land.git Land
git submodule add ssh://git@github.com/CodeEditorLand/LandAnacondaExtensionPack.git LandAnacondaExtensionPack
git submodule add ssh://git@github.com/CodeEditorLand/LandAnycode.git LandAnycode
git submodule add ssh://git@github.com/CodeEditorLand/LandApimanagement.git LandApimanagement
git submodule add ssh://git@github.com/CodeEditorLand/LandAppcenter.git LandAppcenter
git submodule add ssh://git@github.com/CodeEditorLand/LandArduino.git LandArduino
git submodule add ssh://git@github.com/CodeEditorLand/LandAsa.git LandAsa
git submodule add ssh://git@github.com/CodeEditorLand/LandAtomKeybindings.git LandAtomKeybindings
git submodule add ssh://git@github.com/CodeEditorLand/LandAutopep8.git LandAutopep8
git submodule add ssh://git@github.com/CodeEditorLand/LandAzureAccount.git LandAzureAccount
git submodule add ssh://git@github.com/CodeEditorLand/LandAzureappservice.git LandAzureappservice
git submodule add ssh://git@github.com/CodeEditorLand/LandAzurearmtools.git LandAzurearmtools
git submodule add ssh://git@github.com/CodeEditorLand/LandAzureAutomation.git LandAzureAutomation
git submodule add ssh://git@github.com/CodeEditorLand/LandAzureBlockchainEthereum.git LandAzureBlockchainEthereum
git submodule add ssh://git@github.com/CodeEditorLand/LandAzurecache.git LandAzurecache
git submodule add ssh://git@github.com/CodeEditorLand/LandAzurecli.git LandAzurecli
git submodule add ssh://git@github.com/CodeEditorLand/LandAzurecognitivesearch.git LandAzurecognitivesearch
git submodule add ssh://git@github.com/CodeEditorLand/LandAzurecontainerapps.git LandAzurecontainerapps
git submodule add ssh://git@github.com/CodeEditorLand/LandAzureeventgrid.git LandAzureeventgrid
git submodule add ssh://git@github.com/CodeEditorLand/LandAzurefunctions.git LandAzurefunctions
git submodule add ssh://git@github.com/CodeEditorLand/LandAzureFunctionsRemoteWebExtension.git LandAzureFunctionsRemoteWebExtension
git submodule add ssh://git@github.com/CodeEditorLand/LandAzurehealthcareapisTools.git LandAzurehealthcareapisTools
git submodule add ssh://git@github.com/CodeEditorLand/LandAzureIotEdge.git LandAzureIotEdge
git submodule add ssh://git@github.com/CodeEditorLand/LandAzureIotToolkit.git LandAzureIotToolkit
git submodule add ssh://git@github.com/CodeEditorLand/LandAzureIotTools.git LandAzureIotTools
git submodule add ssh://git@github.com/CodeEditorLand/LandAzurelogicapps.git LandAzurelogicapps
git submodule add ssh://git@github.com/CodeEditorLand/LandAzurePack.git LandAzurePack
git submodule add ssh://git@github.com/CodeEditorLand/LandAzureresourcegroups.git LandAzureresourcegroups
git submodule add ssh://git@github.com/CodeEditorLand/LandAzureserverlesspack.git LandAzureserverlesspack
git submodule add ssh://git@github.com/CodeEditorLand/LandAzurespringcloud.git LandAzurespringcloud
git submodule add ssh://git@github.com/CodeEditorLand/LandAzurestaticwebapps.git LandAzurestaticwebapps
git submodule add ssh://git@github.com/CodeEditorLand/LandAzurestorage.git LandAzurestorage
git submodule add ssh://git@github.com/CodeEditorLand/LandAzuretools.git LandAzuretools
git submodule add ssh://git@github.com/CodeEditorLand/LandAzurevirtualmachines.git LandAzurevirtualmachines
git submodule add ssh://git@github.com/CodeEditorLand/LandBackspace.git LandBackspace
git submodule add ssh://git@github.com/CodeEditorLand/LandBisect.git LandBisect
git submodule add ssh://git@github.com/CodeEditorLand/LandBlackFormatter.git LandBlackFormatter
git submodule add ssh://git@github.com/CodeEditorLand/LandBracketsKeybindings.git LandBracketsKeybindings
git submodule add ssh://git@github.com/CodeEditorLand/LandBracketsPack.git LandBracketsPack
git submodule add ssh://git@github.com/CodeEditorLand/LandCdp.git LandCdp
git submodule add ssh://git@github.com/CodeEditorLand/LandCdpProxy.git LandCdpProxy
git submodule add ssh://git@github.com/CodeEditorLand/LandChromeDebug.git LandChromeDebug
git submodule add ssh://git@github.com/CodeEditorLand/LandChromeDebugCore.git LandChromeDebugCore
git submodule add ssh://git@github.com/CodeEditorLand/LandCmakeTools.git LandCmakeTools
git submodule add ssh://git@github.com/CodeEditorLand/LandCmakeToolsApi.git LandCmakeToolsApi
git submodule add ssh://git@github.com/CodeEditorLand/LandCodicons.git LandCodicons
git submodule add ssh://git@github.com/CodeEditorLand/LandComment.git LandComment
git submodule add ssh://git@github.com/CodeEditorLand/LandCopilotRelease.git LandCopilotRelease
git submodule add ssh://git@github.com/CodeEditorLand/LandCordova.git LandCordova
git submodule add ssh://git@github.com/CodeEditorLand/LandCosmosdb.git LandCosmosdb
git submodule add ssh://git@github.com/CodeEditorLand/LandCosmosdbgraph.git LandCosmosdbgraph
git submodule add ssh://git@github.com/CodeEditorLand/LandCourseSample.git LandCourseSample
git submodule add ssh://git@github.com/CodeEditorLand/LandCpptools.git LandCpptools
git submodule add ssh://git@github.com/CodeEditorLand/LandCpptoolsApi.git LandCpptoolsApi
git submodule add ssh://git@github.com/CodeEditorLand/LandCss.git LandCss
git submodule add ssh://git@github.com/CodeEditorLand/LandCssLanguageservice.git LandCssLanguageservice
git submodule add ssh://git@github.com/CodeEditorLand/LandCustomData.git LandCustomData
git submodule add ssh://git@github.com/CodeEditorLand/LandDapr.git LandDapr
git submodule add ssh://git@github.com/CodeEditorLand/LandDataWrangler.git LandDataWrangler
git submodule add ssh://git@github.com/CodeEditorLand/LandDebugadapterNode.git LandDebugadapterNode
git submodule add ssh://git@github.com/CodeEditorLand/LandDeployAzure.git LandDeployAzure
git submodule add ssh://git@github.com/CodeEditorLand/LandDevChromeLauncher.git LandDevChromeLauncher
git submodule add ssh://git@github.com/CodeEditorLand/LandDevContainers.git LandDevContainers
git submodule add ssh://git@github.com/CodeEditorLand/LandDiagnosticTools.git LandDiagnosticTools
git submodule add ssh://git@github.com/CodeEditorLand/LandDiscussions.git LandDiscussions
git submodule add ssh://git@github.com/CodeEditorLand/LandDocker.git LandDocker
git submodule add ssh://git@github.com/CodeEditorLand/LandDockerExtensibility.git LandDockerExtensibility
git submodule add ssh://git@github.com/CodeEditorLand/LandDocs.git LandDocs
git submodule add ssh://git@github.com/CodeEditorLand/LandDocsArchive.git LandDocsArchive
git submodule add ssh://git@github.com/CodeEditorLand/LandDocsAuthoring.git LandDocsAuthoring
git submodule add ssh://git@github.com/CodeEditorLand/LandDotnettools.git LandDotnettools
git submodule add ssh://git@github.com/CodeEditorLand/LandDtdl.git LandDtdl
git submodule add ssh://git@github.com/CodeEditorLand/LandDts.git LandDts
git submodule add ssh://git@github.com/CodeEditorLand/LandDwarfDebugging.git LandDwarfDebugging
git submodule add ssh://git@github.com/CodeEditorLand/LandDwarfDebuggingExt.git LandDwarfDebuggingExt
git submodule add ssh://git@github.com/CodeEditorLand/LandEdgeDebug.git LandEdgeDebug
git submodule add ssh://git@github.com/CodeEditorLand/LandEdgeDebug2.git LandEdgeDebug2
git submodule add ssh://git@github.com/CodeEditorLand/LandEdgeDevtools.git LandEdgeDevtools
git submodule add ssh://git@github.com/CodeEditorLand/LandEdgeDevtoolsNetwork.git LandEdgeDevtoolsNetwork
git submodule add ssh://git@github.com/CodeEditorLand/LandEditorconfig.git LandEditorconfig
git submodule add ssh://git@github.com/CodeEditorLand/LandEmbeddedTools.git LandEmbeddedTools
git submodule add ssh://git@github.com/CodeEditorLand/LandEmmetHelper.git LandEmmetHelper
git submodule add ssh://git@github.com/CodeEditorLand/LandEmmetLegacy.git LandEmmetLegacy
git submodule add ssh://git@github.com/CodeEditorLand/LandEslint.git LandEslint
git submodule add ssh://git@github.com/CodeEditorLand/LandExplorerCommand.git LandExplorerCommand
git submodule add ssh://git@github.com/CodeEditorLand/LandExtensionLand.git LandExtensionLand
git submodule add ssh://git@github.com/CodeEditorLand/LandExtensionRecommender.git LandExtensionRecommender
git submodule add ssh://git@github.com/CodeEditorLand/LandExtensionSamples.git LandExtensionSamples
git submodule add ssh://git@github.com/CodeEditorLand/LandExtensionTelemetry.git LandExtensionTelemetry
git submodule add ssh://git@github.com/CodeEditorLand/LandExtensionTestRunner.git LandExtensionTestRunner
git submodule add ssh://git@github.com/CodeEditorLand/LandFigmaIcons.git LandFigmaIcons
git submodule add ssh://git@github.com/CodeEditorLand/LandFigmaToolkit.git LandFigmaToolkit
git submodule add ssh://git@github.com/CodeEditorLand/LandFileDownloader.git LandFileDownloader
git submodule add ssh://git@github.com/CodeEditorLand/LandFileDownloaderApi.git LandFileDownloaderApi
git submodule add ssh://git@github.com/CodeEditorLand/LandFilewatcherWindows.git LandFilewatcherWindows
git submodule add ssh://git@github.com/CodeEditorLand/LandFlake8.git LandFlake8
git submodule add ssh://git@github.com/CodeEditorLand/LandGather.git LandGather
git submodule add ssh://git@github.com/CodeEditorLand/LandGeneratorCode.git LandGeneratorCode
git submodule add ssh://git@github.com/CodeEditorLand/LandGeneratorCodeJavascript.git LandGeneratorCodeJavascript
git submodule add ssh://git@github.com/CodeEditorLand/LandGithubIssueNotebooks.git LandGithubIssueNotebooks
git submodule add ssh://git@github.com/CodeEditorLand/LandGithubIssuesPrs.git LandGithubIssuesPrs
git submodule add ssh://git@github.com/CodeEditorLand/LandGithubTriageActions.git LandGithubTriageActions
git submodule add ssh://git@github.com/CodeEditorLand/LandGithubTriageExtension.git LandGithubTriageExtension
git submodule add ssh://git@github.com/CodeEditorLand/LandGo.git LandGo
git submodule add ssh://git@github.com/CodeEditorLand/LandGradle.git LandGradle
git submodule add ssh://git@github.com/CodeEditorLand/LandGrammarUpdater.git LandGrammarUpdater
git submodule add ssh://git@github.com/CodeEditorLand/LandGulpElectron.git LandGulpElectron
git submodule add ssh://git@github.com/CodeEditorLand/LandHexeditor.git LandHexeditor
git submodule add ssh://git@github.com/CodeEditorLand/LandHtmlhint.git LandHtmlhint
git submodule add ssh://git@github.com/CodeEditorLand/LandHtmlLanguageservice.git LandHtmlLanguageservice
git submodule add ssh://git@github.com/CodeEditorLand/LandHtmltagwrap.git LandHtmltagwrap
git submodule add ssh://git@github.com/CodeEditorLand/LandHydrate.git LandHydrate
git submodule add ssh://git@github.com/CodeEditorLand/LandIcons.git LandIcons
git submodule add ssh://git@github.com/CodeEditorLand/LandIconvLiteUmd.git LandIconvLiteUmd
git submodule add ssh://git@github.com/CodeEditorLand/LandIosWebDebug.git LandIosWebDebug
git submodule add ssh://git@github.com/CodeEditorLand/LandIotWorkbench.git LandIotWorkbench
git submodule add ssh://git@github.com/CodeEditorLand/LandIsort.git LandIsort
git submodule add ssh://git@github.com/CodeEditorLand/LandJavaDebug.git LandJavaDebug
git submodule add ssh://git@github.com/CodeEditorLand/LandJavaDependency.git LandJavaDependency
git submodule add ssh://git@github.com/CodeEditorLand/LandJavaInstaller.git LandJavaInstaller
git submodule add ssh://git@github.com/CodeEditorLand/LandJavaPack.git LandJavaPack
git submodule add ssh://git@github.com/CodeEditorLand/LandJavaTest.git LandJavaTest
git submodule add ssh://git@github.com/CodeEditorLand/LandJsAtomGrammar.git LandJsAtomGrammar
git submodule add ssh://git@github.com/CodeEditorLand/LandJscs.git LandJscs
git submodule add ssh://git@github.com/CodeEditorLand/LandJsDebug.git LandJsDebug
git submodule add ssh://git@github.com/CodeEditorLand/LandJsDebugBrowsers.git LandJsDebugBrowsers
git submodule add ssh://git@github.com/CodeEditorLand/LandJsDebugCompanion.git LandJsDebugCompanion
git submodule add ssh://git@github.com/CodeEditorLand/LandJshint.git LandJshint
git submodule add ssh://git@github.com/CodeEditorLand/LandJSON.tmLanguage.git LandJSON.tmLanguage
git submodule add ssh://git@github.com/CodeEditorLand/LandJsonLanguageservice.git LandJsonLanguageservice
git submodule add ssh://git@github.com/CodeEditorLand/LandJsProfileVisualizer.git LandJsProfileVisualizer
git submodule add ssh://git@github.com/CodeEditorLand/LandJupyter.git LandJupyter
git submodule add ssh://git@github.com/CodeEditorLand/LandJupyterCellTags.git LandJupyterCellTags
git submodule add ssh://git@github.com/CodeEditorLand/LandJupyterHub.git LandJupyterHub
git submodule add ssh://git@github.com/CodeEditorLand/LandJupyterIpywidgets.git LandJupyterIpywidgets
git submodule add ssh://git@github.com/CodeEditorLand/LandJupyterKeymap.git LandJupyterKeymap
git submodule add ssh://git@github.com/CodeEditorLand/LandJupyterLspMiddleware.git LandJupyterLspMiddleware
git submodule add ssh://git@github.com/CodeEditorLand/LandJupyterPowertoys.git LandJupyterPowertoys
git submodule add ssh://git@github.com/CodeEditorLand/LandJupyterSlideshow.git LandJupyterSlideshow
git submodule add ssh://git@github.com/CodeEditorLand/LandJvmTools.git LandJvmTools
git submodule add ssh://git@github.com/CodeEditorLand/LandL10n.git LandL10n
git submodule add ssh://git@github.com/CodeEditorLand/LandLanguagedetection.git LandLanguagedetection
git submodule add ssh://git@github.com/CodeEditorLand/LandLanguageserverNode.git LandLanguageserverNode
git submodule add ssh://git@github.com/CodeEditorLand/LandLanguageserverProtocolFoldingprovider.git LandLanguageserverProtocolFoldingprovider
git submodule add ssh://git@github.com/CodeEditorLand/LandLaTeX.git LandLaTeX
git submodule add ssh://git@github.com/CodeEditorLand/LandLinuxBuildAgent.git LandLinuxBuildAgent
git submodule add ssh://git@github.com/CodeEditorLand/LandLivepreview.git LandLivepreview
git submodule add ssh://git@github.com/CodeEditorLand/LandLoader.git LandLoader
git submodule add ssh://git@github.com/CodeEditorLand/LandLoc.git LandLoc
git submodule add ssh://git@github.com/CodeEditorLand/LandLocDeprecated.git LandLocDeprecated
git submodule add ssh://git@github.com/CodeEditorLand/LandLombok.git LandLombok
git submodule add ssh://git@github.com/CodeEditorLand/LandLsifExtension.git LandLsifExtension
git submodule add ssh://git@github.com/CodeEditorLand/LandMakecode.git LandMakecode
git submodule add ssh://git@github.com/CodeEditorLand/LandMakefileTools.git LandMakefileTools
git submodule add ssh://git@github.com/CodeEditorLand/LandMarkdownItKatex.git LandMarkdownItKatex
git submodule add ssh://git@github.com/CodeEditorLand/LandMarkdownLanguageservice.git LandMarkdownLanguageservice
git submodule add ssh://git@github.com/CodeEditorLand/LandMarkdownNotebook.git LandMarkdownNotebook
git submodule add ssh://git@github.com/CodeEditorLand/LandMarkdownTmGrammar.git LandMarkdownTmGrammar
git submodule add ssh://git@github.com/CodeEditorLand/LandMaven.git LandMaven
git submodule add ssh://git@github.com/CodeEditorLand/LandMDTools.git LandMDTools
git submodule add ssh://git@github.com/CodeEditorLand/LandMezzurite.git LandMezzurite
git submodule add ssh://git@github.com/CodeEditorLand/LandMinimist.git LandMinimist
git submodule add ssh://git@github.com/CodeEditorLand/LandMockDebug.git LandMockDebug
git submodule add ssh://git@github.com/CodeEditorLand/LandMongodb.git LandMongodb
git submodule add ssh://git@github.com/CodeEditorLand/LandMonoDebug.git LandMonoDebug
git submodule add ssh://git@github.com/CodeEditorLand/LandMssql.git LandMssql
git submodule add ssh://git@github.com/CodeEditorLand/LandMypy.git LandMypy
git submodule add ssh://git@github.com/CodeEditorLand/LandNls.git LandNls
git submodule add ssh://git@github.com/CodeEditorLand/LandNlsDev.git LandNlsDev
git submodule add ssh://git@github.com/CodeEditorLand/LandNodeAzurePack.git LandNodeAzurePack
git submodule add ssh://git@github.com/CodeEditorLand/LandNodebook.git LandNodebook
git submodule add ssh://git@github.com/CodeEditorLand/LandNodeDebug.git LandNodeDebug
git submodule add ssh://git@github.com/CodeEditorLand/LandNodeDebug2.git LandNodeDebug2
git submodule add ssh://git@github.com/CodeEditorLand/LandNodeSqlite3.git LandNodeSqlite3
git submodule add ssh://git@github.com/CodeEditorLand/LandNotebookErrorOverlay.git LandNotebookErrorOverlay
git submodule add ssh://git@github.com/CodeEditorLand/LandNotebookRenderers.git LandNotebookRenderers
git submodule add ssh://git@github.com/CodeEditorLand/LandNotebookRendererStarter.git LandNotebookRendererStarter
git submodule add ssh://git@github.com/CodeEditorLand/LandNotebookTestdata.git LandNotebookTestdata
git submodule add ssh://git@github.com/CodeEditorLand/LandNotepadplusplusKeybindings.git LandNotepadplusplusKeybindings
git submodule add ssh://git@github.com/CodeEditorLand/LandNpmScripts.git LandNpmScripts
git submodule add ssh://git@github.com/CodeEditorLand/LandOcticonsFont.git LandOcticonsFont
git submodule add ssh://git@github.com/CodeEditorLand/LandOnedriveBrowser.git LandOnedriveBrowser
git submodule add ssh://git@github.com/CodeEditorLand/LandOniguruma.git LandOniguruma
git submodule add ssh://git@github.com/CodeEditorLand/LandOpensslPrebuilt.git LandOpensslPrebuilt
git submodule add ssh://git@github.com/CodeEditorLand/LandPerf.git LandPerf
git submodule add ssh://git@github.com/CodeEditorLand/LandPerfBot.git LandPerfBot
git submodule add ssh://git@github.com/CodeEditorLand/LandPlatformSpecificSample.git LandPlatformSpecificSample
git submodule add ssh://git@github.com/CodeEditorLand/LandPolicyWatcher.git LandPolicyWatcher
git submodule add ssh://git@github.com/CodeEditorLand/LandPostgresql.git LandPostgresql
git submodule add ssh://git@github.com/CodeEditorLand/LandPowerquery.git LandPowerquery
git submodule add ssh://git@github.com/CodeEditorLand/LandPowerquerySdk.git LandPowerquerySdk
git submodule add ssh://git@github.com/CodeEditorLand/LandProxyAgent.git LandProxyAgent
git submodule add ssh://git@github.com/CodeEditorLand/LandPullRequestGithub.git LandPullRequestGithub
git submodule add ssh://git@github.com/CodeEditorLand/LandPwaAnalyzer.git LandPwaAnalyzer
git submodule add ssh://git@github.com/CodeEditorLand/LandPylint.git LandPylint
git submodule add ssh://git@github.com/CodeEditorLand/LandPython.git LandPython
git submodule add ssh://git@github.com/CodeEditorLand/LandPythonDebugger.git LandPythonDebugger
git submodule add ssh://git@github.com/CodeEditorLand/LandPythonDeviceSimulator.git LandPythonDeviceSimulator
git submodule add ssh://git@github.com/CodeEditorLand/LandPythonDsExtensionPack.git LandPythonDsExtensionPack
git submodule add ssh://git@github.com/CodeEditorLand/LandPythonInstaller.git LandPythonInstaller
git submodule add ssh://git@github.com/CodeEditorLand/LandPythonToolsExtensionTemplate.git LandPythonToolsExtensionTemplate
git submodule add ssh://git@github.com/CodeEditorLand/LandPythonWebWasm.git LandPythonWebWasm
git submodule add ssh://git@github.com/CodeEditorLand/LandReactNative.git LandReactNative
git submodule add ssh://git@github.com/CodeEditorLand/LandReactSample.git LandReactSample
git submodule add ssh://git@github.com/CodeEditorLand/LandRecipes.git LandRecipes
git submodule add ssh://git@github.com/CodeEditorLand/LandReferencesView.git LandReferencesView
git submodule add ssh://git@github.com/CodeEditorLand/LandRemoteRelease.git LandRemoteRelease
git submodule add ssh://git@github.com/CodeEditorLand/LandRemoteRepositoriesGithub.git LandRemoteRepositoriesGithub
git submodule add ssh://git@github.com/CodeEditorLand/LandRemoteTryCpp.git LandRemoteTryCpp
git submodule add ssh://git@github.com/CodeEditorLand/LandRemoteTryDotnet.git LandRemoteTryDotnet
git submodule add ssh://git@github.com/CodeEditorLand/LandRemoteTryGo.git LandRemoteTryGo
git submodule add ssh://git@github.com/CodeEditorLand/LandRemoteTryJava.git LandRemoteTryJava
git submodule add ssh://git@github.com/CodeEditorLand/LandRemoteTryNode.git LandRemoteTryNode
git submodule add ssh://git@github.com/CodeEditorLand/LandRemoteTryPhp.git LandRemoteTryPhp
git submodule add ssh://git@github.com/CodeEditorLand/LandRemoteTryPython.git LandRemoteTryPython
git submodule add ssh://git@github.com/CodeEditorLand/LandRemoteTryRust.git LandRemoteTryRust
git submodule add ssh://git@github.com/CodeEditorLand/LandRemoteTrySqlserver.git LandRemoteTrySqlserver
git submodule add ssh://git@github.com/CodeEditorLand/LandRemoteWslRecommender.git LandRemoteWslRecommender
git submodule add ssh://git@github.com/CodeEditorLand/LandResharperKeybindings.git LandResharperKeybindings
git submodule add ssh://git@github.com/CodeEditorLand/LandRipgrep.git LandRipgrep
git submodule add ssh://git@github.com/CodeEditorLand/LandRussh.git LandRussh
git submodule add ssh://git@github.com/CodeEditorLand/LandSamples.git LandSamples
git submodule add ssh://git@github.com/CodeEditorLand/LandSCMBuilders.git LandSCMBuilders
git submodule add ssh://git@github.com/CodeEditorLand/LandSecretServiceRs.git LandSecretServiceRs
git submodule add ssh://git@github.com/CodeEditorLand/LandSelfhostTestProvider.git LandSelfhostTestProvider
git submodule add ssh://git@github.com/CodeEditorLand/LandSerialMonitor.git LandSerialMonitor
git submodule add ssh://git@github.com/CodeEditorLand/LandServiceFabricReliableServices.git LandServiceFabricReliableServices
git submodule add ssh://git@github.com/CodeEditorLand/LandServiceStatus.git LandServiceStatus
git submodule add ssh://git@github.com/CodeEditorLand/LandSimpleJupyterNotebook.git LandSimpleJupyterNotebook
git submodule add ssh://git@github.com/CodeEditorLand/LandSmoketestCheck.git LandSmoketestCheck
git submodule add ssh://git@github.com/CodeEditorLand/LandSmoketestExpress.git LandSmoketestExpress
git submodule add ssh://git@github.com/CodeEditorLand/LandspacesQuickstart.git LandspacesQuickstart
git submodule add ssh://git@github.com/CodeEditorLand/LandSpellCheck.git LandSpellCheck
git submodule add ssh://git@github.com/CodeEditorLand/LandSpringBootDashboard.git LandSpringBootDashboard
git submodule add ssh://git@github.com/CodeEditorLand/LandSpringInitializr.git LandSpringInitializr
git submodule add ssh://git@github.com/CodeEditorLand/LandStac.git LandStac
git submodule add ssh://git@github.com/CodeEditorLand/LandSublimeKeybindings.git LandSublimeKeybindings
git submodule add ssh://git@github.com/CodeEditorLand/LandTasAngular.git LandTasAngular
git submodule add ssh://git@github.com/CodeEditorLand/LandTasExpress.git LandTasExpress
git submodule add ssh://git@github.com/CodeEditorLand/LandTasVue.git LandTasVue
git submodule add ssh://git@github.com/CodeEditorLand/LandTeam.git LandTeam
git submodule add ssh://git@github.com/CodeEditorLand/LandTelemetryExtractor.git LandTelemetryExtractor
git submodule add ssh://git@github.com/CodeEditorLand/LandTensorboard.git LandTensorboard
git submodule add ssh://git@github.com/CodeEditorLand/LandTest.git LandTest
git submodule add ssh://git@github.com/CodeEditorLand/LandTestAdapterConverter.git LandTestAdapterConverter
git submodule add ssh://git@github.com/CodeEditorLand/LandTestCli.git LandTestCli
git submodule add ssh://git@github.com/CodeEditorLand/Landtestcover.git Landtestcover
git submodule add ssh://git@github.com/CodeEditorLand/LandTestWeb.git LandTestWeb
git submodule add ssh://git@github.com/CodeEditorLand/LandTextbuffer.git LandTextbuffer
git submodule add ssh://git@github.com/CodeEditorLand/LandTextmate.git LandTextmate
git submodule add ssh://git@github.com/CodeEditorLand/LandThemeColorConsumer.git LandThemeColorConsumer
git submodule add ssh://git@github.com/CodeEditorLand/LandThemes.git LandThemes
git submodule add ssh://git@github.com/CodeEditorLand/LandThemeTester.git LandThemeTester
git submodule add ssh://git@github.com/CodeEditorLand/LandTipsAndTricks.git LandTipsAndTricks
git submodule add ssh://git@github.com/CodeEditorLand/LandTmdl.git LandTmdl
git submodule add ssh://git@github.com/CodeEditorLand/LandToolsForAi.git LandToolsForAi
git submodule add ssh://git@github.com/CodeEditorLand/LandTslint.git LandTslint
git submodule add ssh://git@github.com/CodeEditorLand/LandTsPackageManager.git LandTsPackageManager
git submodule add ssh://git@github.com/CodeEditorLand/LandTsTslint.git LandTsTslint
git submodule add ssh://git@github.com/CodeEditorLand/LandTye.git LandTye
git submodule add ssh://git@github.com/CodeEditorLand/LandTypescriptNext.git LandTypescriptNext
git submodule add ssh://git@github.com/CodeEditorLand/LandTypescriptTslintPlugin.git LandTypescriptTslintPlugin
git submodule add ssh://git@github.com/CodeEditorLand/LandUri.git LandUri
git submodule add ssh://git@github.com/CodeEditorLand/LandV8HeapTools.git LandV8HeapTools
git submodule add ssh://git@github.com/CodeEditorLand/LandVsce.git LandVsce
git submodule add ssh://git@github.com/CodeEditorLand/LandVsKeybindings.git LandVsKeybindings
git submodule add ssh://git@github.com/CodeEditorLand/LandWasm.git LandWasm
git submodule add ssh://git@github.com/CodeEditorLand/LandWebPlayground.git LandWebPlayground
git submodule add ssh://git@github.com/CodeEditorLand/LandWebviewUiToolkit.git LandWebviewUiToolkit
git submodule add ssh://git@github.com/CodeEditorLand/LandWebviewUiToolkitSamples.git LandWebviewUiToolkitSamples
git submodule add ssh://git@github.com/CodeEditorLand/LandWiki.git LandWiki
git submodule add ssh://git@github.com/CodeEditorLand/LandWin32AppContainerTokens.git LandWin32AppContainerTokens
git submodule add ssh://git@github.com/CodeEditorLand/LandWindowsCaCerts.git LandWindowsCaCerts
git submodule add ssh://git@github.com/CodeEditorLand/LandWindowsProcessTree.git LandWindowsProcessTree
git submodule add ssh://git@github.com/CodeEditorLand/LandWindowsRegistry.git LandWindowsRegistry
git submodule add ssh://git@github.com/CodeEditorLand/LandWinsta11er.git LandWinsta11er
git submodule add ssh://git@github.com/CodeEditorLand/LandWordcount.git LandWordcount
git submodule add ssh://git@github.com/CodeEditorLand/LandZeromq.git LandZeromq
git submodule add ssh://git@github.com/CodeEditorLand/Linkcheckermd.git Linkcheckermd
git submodule add ssh://git@github.com/CodeEditorLand/MonacoEditor.git MonacoEditor
git submodule add ssh://git@github.com/CodeEditorLand/NodeRequestLight.git NodeRequestLight
git submodule add ssh://git@github.com/CodeEditorLand/PlaywrightLand.git PlaywrightLand
git submodule add ssh://git@github.com/CodeEditorLand/PowerplatformLand.git PowerplatformLand
git submodule add ssh://git@github.com/CodeEditorLand/PowerplatformLandLab.git PowerplatformLandLab
git submodule add ssh://git@github.com/CodeEditorLand/PSDocsLand.git PSDocsLand
git submodule add ssh://git@github.com/CodeEditorLand/PSRuleLand.git PSRuleLand
git submodule add ssh://git@github.com/CodeEditorLand/Pvscbot.git Pvscbot
git submodule add ssh://git@github.com/CodeEditorLand/PythonSampleLandDjangoTutorial.git PythonSampleLandDjangoTutorial
git submodule add ssh://git@github.com/CodeEditorLand/PythonSampleLandFastapiTutorial.git PythonSampleLandFastapiTutorial
git submodule add ssh://git@github.com/CodeEditorLand/PythonSampleLandFlaskTutorial.git PythonSampleLandFlaskTutorial
git submodule add ssh://git@github.com/CodeEditorLand/Quantum.git Quantum
git submodule add ssh://git@github.com/CodeEditorLand/SarifLandExtension.git SarifLandExtension
git submodule add ssh://git@github.com/CodeEditorLand/ScopestudioLand.git ScopestudioLand
git submodule add ssh://git@github.com/CodeEditorLand/SynapseLand.git SynapseLand
git submodule add ssh://git@github.com/CodeEditorLand/ThemeConverterForVs.git ThemeConverterForVs
git submodule add ssh://git@github.com/CodeEditorLand/TypeScriptLandExtensions.git TypeScriptLandExtensions
